# Generated by Django 3.0.5 on 2020-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiir', '0005_auto_20200505_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='is_fermat',
            field=models.BooleanField(default=False),
        ),
    ]
